name: Code checks
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd backend/
          pip install --upgrade pip
          pip install -r requirements.dev.txt
      - name: Lint
        run: |
          cd backend/
          flake8
  test:
    name: Code tests
    needs: lint
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DATABASE_ENGINE: ${{ secrets.DATABASE_ENGINE }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd backend/
          pip install --upgrade pip
          pip install psycopg2-binary==2.9.5 --use-pep517
          pip install -r requirements.txt
      - name: Run migrations
        run: |
          cd backend/app/
          python manage.py makemigrations
      - name: Test
        run: |
          cd backend/app/
          python manage.py test
